import os
dirpath = os.path.dirname(os.path.abspath(__file__))

Q = chr(34)

lines = []
lines.append('using System;')
lines.append('using UnityEngine;')
lines.append('')
lines.append('public sealed class TauntSkillRuntime : MonoBehaviour')
lines.append('{')
lines.append('    private SkillCastContext context;')
lines.append('    private TauntSkillPayloadDef payload;')
lines.append('    private CharacterAnimBrain animBrain;')
lines.append('    private int requestId;')
lines.append('    private float expireAt;')
lines.append('    private bool initialized;')
lines.append('    private bool shuttingDown;')
lines.append('')
lines.append('    public void Initialize(SkillCastContext castContext, TauntSkillPayloadDef payloadDef)')
lines.append('    {')
lines.append('        context = castContext;')
lines.append('        payload = payloadDef;')
lines.append('        animBrain = castContext != null ? castContext.AnimBrain : null;')
lines.append('        requestId = castContext != null ? castContext.RequestId : 0;')
lines.append('        expireAt = Time.time + (payloadDef != null ? payloadDef.Duration + 5f : 10f);')
lines.append('')
lines.append('        if (animBrain == null || payloadDef == null)')
lines.append('        {')
lines.append('            Shutdown();')
lines.append('            return;')
lines.append('        }')
lines.append('')
lines.append('        animBrain.SkillTimelineEventRaised += OnSkillTimelineEventRaised;')
lines.append('        animBrain.SkillCastInterrupted += OnSkillCastInterrupted;')
lines.append('        initialized = true;')
lines.append('    }')
lines.append('')
lines.append('    void Update()')
lines.append('    {')
lines.append('        if (!initialized || shuttingDown)')
lines.append('            return;')
lines.append('')
lines.append('        if (Time.time >= expireAt)')
lines.append('        {')
lines.append('            Shutdown();')
lines.append('            return;')
lines.append('        }')
lines.append('')
lines.append('        if (animBrain != null && requestId > 0)')
lines.append('        {')
lines.append('            if (!animBrain.TryGetActiveSkillNormalizedTime(requestId, out _))')
lines.append('            {')
lines.append('                Shutdown();')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    void OnDisable()')
lines.append('    {')
lines.append('        Unsubscribe();')
lines.append('    }')
lines.append('')
lines.append('    void OnDestroy()')
lines.append('    {')
lines.append('        Unsubscribe();')
lines.append('    }')
lines.append('')
lines.append('    void Unsubscribe()')
lines.append('    {')
lines.append('        if (animBrain == null)')
lines.append('            return;')
lines.append('')
lines.append('        animBrain.SkillTimelineEventRaised -= OnSkillTimelineEventRaised;')
lines.append('        animBrain.SkillCastInterrupted -= OnSkillCastInterrupted;')
lines.append('    }')
lines.append('')
lines.append('    void OnSkillTimelineEventRaised(int raisedRequestId, CombatTimelineEventName eventName)')
lines.append('    {')
lines.append('        if (!initialized || shuttingDown)')
lines.append('            return;')
lines.append('')
lines.append('        if (raisedRequestId != requestId)')
lines.append('            return;')
lines.append('')
lines.append('        if (eventName == CombatTimelineEventName.TauntApply)')
lines.append('        {')
lines.append('            PerformTaunt();')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    void OnSkillCastInterrupted(int interruptedRequestId)')
lines.append('    {')
lines.append('        if (interruptedRequestId != requestId)')
lines.append('            return;')
lines.append('')
lines.append('        Shutdown();')
lines.append('    }')
lines.append('')
lines.append('    void PerformTaunt()')
lines.append('    {')
lines.append('        if (payload == null || context == null)')
lines.append('            return;')
lines.append('')
lines.append('        Transform casterRoot = context.CasterRoot;')
lines.append('        Vector3 origin = casterRoot != null ? casterRoot.position : transform.position;')
lines.append('        float searchRadius = payload.Radius;')
lines.append('        LayerMask targetMask = payload.TargetLayers;')
lines.append('        float tauntDuration = payload.Duration;')
lines.append('')
lines.append('        Collider[] hits = Physics.OverlapSphere(origin, searchRadius, targetMask);')
lines.append('        if (hits == null || hits.Length == 0)')
lines.append('            return;')
lines.append('')
lines.append('        for (int i = 0; i < hits.Length; i++)')
lines.append('        {')
lines.append('            Collider hit = hits[i];')
lines.append('            if (hit == null)')
lines.append('                continue;')
lines.append('')
lines.append('            if (BelongsToCaster(hit.transform))')
lines.append('                continue;')
lines.append('')
lines.append('            if (payload.RequireLineOfSight)')
lines.append('            {')
lines.append('                Vector3 hitPoint = hit.bounds.center;')
lines.append('                Vector3 direction = hitPoint - origin;')
lines.append('                if (Physics.Raycast(origin, direction.normalized, direction.magnitude, Physics.DefaultRaycastLayers, QueryTriggerInteraction.Ignore))')
lines.append('                    continue;')
lines.append('            }')
lines.append('')
lines.append('            AITargetSensor sensor = hit.GetComponentInParent<AITargetSensor>();')
lines.append('            if (sensor == null)')
lines.append('                continue;')
lines.append('')
lines.append('            sensor.ApplyTaunt(sensor.transform, tauntDuration);')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    bool BelongsToCaster(Transform other)')
lines.append('    {')
lines.append('        Transform casterRoot = context != null ? context.CasterRoot : null;')
lines.append('        if (casterRoot == null || other == null)')
lines.append('            return false;')
lines.append('')
lines.append('        return other == casterRoot || other.IsChildOf(casterRoot) || other.root == casterRoot;')
lines.append('    }')
lines.append('')
lines.append('    void Shutdown()')
lines.append('    {')
lines.append('        if (shuttingDown)')
lines.append('            return;')
lines.append('')
lines.append('        shuttingDown = true;')
lines.append('        Unsubscribe();')
lines.append('        Destroy(gameObject);')
lines.append('    }')
lines.append('}')
lines.append('')
payload_path = os.path.join(dirpath, 'Player', 'Skill', 'Payloads', 'TauntSkillRuntime.cs')
with open(payload_path, 'w', encoding='utf-8') as f:
    f.write(chr(10).join(lines))
print('OK')