import os
dirpath = os.path.dirname(os.path.abspath(__file__))

Q = chr(34)

payload_lines = []
payload_lines.append('using System.Collections.Generic;')
payload_lines.append('using Sirenix.OdinInspector;')
payload_lines.append('using UnityEngine;')
payload_lines.append('')
payload_lines.append('[HideMonoScript]')
payload_lines.append('public sealed class TauntSkillPayloadDef : SkillPayloadDef')
payload_lines.append('{')
payload_lines.append('    [PropertyOrder(-20)]')
payload_lines.append('    [InfoBox(' + Q + 'Spawns a runtime listener that applies taunt to enemies in range when the TauntApply timeline event fires.' + Q + ')]')
payload_lines.append('    [SerializeField, BoxGroup(' + Q + 'Setup' + Q + '), Min(0f)]')
payload_lines.append('    [LabelText(' + Q + 'Radius' + Q + '), SuffixLabel(' + Q + 'm' + Q + ')]')
payload_lines.append('    private float radius = 10f;')
payload_lines.append('')
payload_lines.append('    [SerializeField, BoxGroup(' + Q + 'Setup' + Q + '), Min(0f)]')
payload_lines.append('    [LabelText(' + Q + 'Duration' + Q + '), SuffixLabel(' + Q + 's' + Q + ')]')
payload_lines.append('    private float duration = 3f;')
payload_lines.append('')
payload_lines.append('    [SerializeField, BoxGroup(' + Q + 'Setup' + Q + '), ToggleLeft]')
payload_lines.append('    [LabelText(' + Q + 'Require Line of Sight' + Q + ')]')
payload_lines.append('    private bool requireLineOfSight = false;')
payload_lines.append('')
payload_lines.append('    [SerializeField, BoxGroup(' + Q + 'Setup' + Q + ')]')
payload_lines.append('    [LabelText(' + Q + 'Target Layers' + Q + ')]')
payload_lines.append('    private LayerMask targetLayers = ~0;')
payload_lines.append('')
payload_lines.append('    public float Radius => radius;')
payload_lines.append('    public float Duration => duration;')
payload_lines.append('    public bool RequireLineOfSight => requireLineOfSight;')
payload_lines.append('    public LayerMask TargetLayers => targetLayers;')
payload_lines.append('')
payload_lines.append('    public override bool RequiresSkillTimelineEvents => true;')
payload_lines.append('')
payload_lines.append('    public override void CollectTimelineEventNames(List<CombatTimelineEventName> eventNames)')
payload_lines.append('    {')
payload_lines.append('        CombatTimelineEventNames.AddUnique(eventNames, CombatTimelineEventName.TauntApply);')
payload_lines.append('    }')
payload_lines.append('')
payload_lines.append('    public override void CollectValidationIssues(List<string> issues)')
payload_lines.append('    {')
payload_lines.append('        if (issues == null)')
payload_lines.append('            return;')
payload_lines.append('')
payload_lines.append('        if (radius <= 0f)')
payload_lines.append('            issues.Add(' + Q + 'Taunt payload has no radius configured.' + Q + ');')
payload_lines.append('')
payload_lines.append('        if (duration <= 0f)')
payload_lines.append('            issues.Add(' + Q + 'Taunt payload has no duration configured.' + Q + ');')
payload_lines.append('')
payload_lines.append('        if (targetLayers.value == 0)')
payload_lines.append('            issues.Add(' + Q + 'Taunt payload has no target layers configured.' + Q + ');')
payload_lines.append('    }')
payload_lines.append('')
payload_lines.append('    public override void Execute(SkillCastContext context)')
payload_lines.append('    {')
payload_lines.append('        if (context == null || context.CasterObject == null)')
payload_lines.append('            return;')
payload_lines.append('')
payload_lines.append('        GameObject host = new GameObject(' + Q + 'TauntSkillRuntime' + Q + ');')
payload_lines.append('        host.transform.SetParent(null);')
payload_lines.append('')
payload_lines.append('        TauntSkillRuntime runtime = host.AddComponent<TauntSkillRuntime>();')
payload_lines.append('        runtime.Initialize(context, this);')
payload_lines.append('    }')
payload_lines.append('}')
payload_lines.append('')
payload_text = chr(10).join(payload_lines)
payload_path = os.path.join(dirpath, 'Player', 'Skill', 'Payloads', 'TauntSkillPayloadDef.cs')
with open(payload_path, 'w', encoding='utf-8') as f:
    f.write(payload_text)
print('OK')