import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'CombatTimelineEventName.cs')
lines = []
lines.append('using Animancer;')
lines.append('')
lines.append('public enum CombatTimelineEventName')
lines.append('{')
lines.append('    None = 0,')
lines.append('')
lines.append('    HitStart = 10,')
lines.append('    HitEnd = 11,')
lines.append('    FootStep = 12,')
lines.append('    SpawnEffect = 13,')
lines.append('    ShakeCamera = 14,')
lines.append('')
lines.append('    TauntApply = 30,')
lines.append('')
lines.append('    Vfx = 20,')
lines.append('')
lines.append('    PreCastOpen = 200,')
lines.append('    PreCastClose = 201,')
lines.append('}')
lines.append('')
lines.append('public static class CombatTimelineEventNames')
lines.append('{')
lines.append('    public static bool IsValid(CombatTimelineEventName eventName)')
lines.append('    {')
lines.append('        return eventName != CombatTimelineEventName.None;')
lines.append('    }')
lines.append('')
lines.append('    public static StringReference ToStringReference(CombatTimelineEventName eventName)')
lines.append('    {')
lines.append('        string animancerEventName = ToAnimancerEventName(eventName);')
lines.append('        return string.IsNullOrWhiteSpace(animancerEventName)')
lines.append('            ? null')
lines.append('            : StringReference.Get(animancerEventName);')
lines.append('    }')
lines.append('')
lines.append('    public static string ToAnimancerEventName(CombatTimelineEventName eventName)')
lines.append('    {')
lines.append('        switch (eventName)')
lines.append('        {')
names = ['HitStart','HitEnd','FootStep','SpawnEffect','ShakeCamera','TauntApply','Vfx','PreCastOpen','PreCastClose']
for n in names:
    lines.append('            case CombatTimelineEventName.' + n + ':')
    lines.append('                return ' + chr(34) + n + chr(34) + ';')
lines.append('        }')
lines.append('')
lines.append('        return eventName == CombatTimelineEventName.None ? null : eventName.ToString();')
lines.append('    }')
lines.append('')
lines.append('    public static void AddUnique(')
lines.append('        System.Collections.Generic.List<CombatTimelineEventName> eventNames,')
lines.append('        CombatTimelineEventName eventName)')
lines.append('    {')
lines.append('        if (eventNames == null || !IsValid(eventName) || eventNames.Contains(eventName))')
lines.append('            return;')
lines.append('')
lines.append('        eventNames.Add(eventName);')
lines.append('    }')
lines.append('')
lines.append('}')
lines.append('')
with open(path, 'w', encoding='utf-8') as f:
    f.write(chr(10).join(lines))
print('OK')